apiVersion: v1
kind: Service
metadata:
  name: devops-project-service
spec:
  selector:
    app: devops-project-app
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer
