apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-project-deployment
  labels:
    app: devops-project-app
spec:
  selector:
    matchLabels:
      app: devops-project-app
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: devops-project-app
    spec:
      containers:
      - name: devops-project
        image: devops-project:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
          - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
