apiVersion: v1
kind: PersistentVolume
metadata:
  name: devops-project-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/devops"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devops-project-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
