on:
  push:

      
jobs:

  linting:
    runs-on: ubuntu-latest
    needs: [git_leak_check]
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Flake8
        run: |
          pip install --upgrade pip
          pip install flake8

      - name: Run Flake8 checks
        run: flake8 src/app_test.py

  markdown_file_check:
   runs-on: ubuntu-latest
   needs: [git_leak_check]
   steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Markdown Link Validation
      uses: ruzickap/action-my-markdown-link-checker@v1.1.2

  editorconfig_lint:
    runs-on: ubuntu-latest
    needs: [git_leak_check]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Editor-Conf-Checker
        run: pip install editorconfig-checker

      - name: Editor-Conf Check
        run: ec -version

     # - name: Check files for EditorConfig compliance
     #  run: ec .
              
  database_migrations: 
    runs-on: ubuntu-latest
    needs: [linting, black_formatting, editorconfig_lint, markdown_file_check]
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: joshuaavalon/flyway-action@v3.0.0
        with:
          url: jdbc:postgresql://postgres:5432/db
          user: user
          password: password
      - run: echo 'testing'

  unit_testing:
    runs-on: ubuntu-latest
    needs: [black_formatting, linting, markdown_file_check, editorconfig_lint]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ./src/requirements.txt

      - name: Run tests
        run: |
          export PYTHONPATH=./src
          python3 -m unittest src/app_test.py
          
  sonar_cloud_test:
    runs-on: ubuntu-latest
    needs: [database_migrations, unit_testing]
    permissions:
     packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v2.0.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}  # Твоят проектен ключ
        SONAR_ORG_KEY: ${{ secrets.SONAR_ORG_KEY }}        # Твоята организация
        SONAR_HOST_URL: "https://sonarcloud.io"

  snyk_scan:
    runs-on: ubuntu-latest
    needs: [database_migrations, unit_testing]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Run Snyk Security Check
        working-directory: ${{github.workspace}}/src
        run: |
          pip install -r requirements.txt
          npm install -g snyk
          snyk auth ${{secrets.SNYK_TOKEN}}
          snyk test
          
  
  git_leak_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Gitleaks check
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  code_cov:
    runs-on: ubuntu-latest
    needs: [database_migrations, unit_testing]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@master
        with:
           python-version: 3.12
     
      - name: Check code coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}     
          working-directory: .

  SecScan2:
     runs-on: ubuntu-latest
     needs: [database_migrations, unit_testing]
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
        
       - name: Perform Scan
         uses: ShiftLeftSecurity/scan-action@master
         with:
           type: "python"
         env:
          WORKSPACE: .
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  codacy_analysis_CLI:
     runs-on: ubuntu-latest
     needs: [database_migrations, unit_testing]
     steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master 

  dependency_check:
   runs-on: ubuntu-latest
   needs: [database_migrations, unit_testing]
   steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install pip-tools
      run: |
        pip install pip-tools
        pip-compile --output-file=requirements.txt requirements.in
        pip install -r requirements.txt

  black_formatting:
    runs-on: ubuntu-latest
    needs: [git_leak_check]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Black
        run: pip install black

      - name: Check formatting with Black
        id: black_check
        run: |
          black --check .
        continue-on-error: true # Позволява job-ът да продължи, дори ако проверката не е успешна

      - name: Apply formatting with Black
        if: steps.black_check.outcome == 'failure' # Форматира кода само ако проверката е неуспешна
        run: black .
          
  image_push:
     runs-on: ubuntu-latest
     needs: [complexity_analysis, sonar_cloud_test, snyk_scan, code_cov, SecScan2, codacy_analysis_CLI, dependency_check, black_formatting]
     permissions:
      packages: write
     steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Clear Docker Cache
        run: docker builder prune -a -f
        
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
      - name: Build an image
        run: docker build -t "python-docker-app" .

      - name: AquaSec Trivy
        uses: aquasecurity/trivy-action@0.13.1
        with:
          image-ref: "python-docker-app"
          scan-ref: .  #its the default code
          exit-code: 1
          timeout: 3m0s
          vuln-type: "os,library" #optional, default
          severity: "CRITICAL"        
        
      - name: Tag an image 
        run: docker tag python-docker-app rositsakostova/python-docker-app:latest

      - name: Push Image to Dockerhub  
        run: docker push rositsakostova/python-docker-app:latest

  complexity_analysis:
     runs-on: ubuntu-latest
     needs: [unit_testing, database_migrations]
     steps:
     - name: Checkout code
       uses: actions/checkout@v3

     - name: Install Radon
       run: pip install radon

     - name: Run Cyclomatic Complexity Check
       run: radon cc src/ -a

  mutation_testing:
   runs-on: ubuntu-latest
   needs: [unit_testing]
   steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Mutmut
      run: pip install mutmut

    - name: Run Mutation Tests
      run: mutmut run --paths-to-mutate src/
