on: 
  push

jobs:

  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Flake8
        run: |
          pip install --upgrade pip
          pip install flake8

      - name: Run Flake8 checks
        run: flake8 src/app_test.py


  editorconfig_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install EditorConfig Checker
        run: |
          curl -sSL https://github.com/editorconfig-checker/editorconfig-checker/releases/latest/download/ec-linux-amd64.tar.gz | tar -xz
          sudo mv ec-linux-amd64 /usr/local/bin/editorconfig-checker

      - name: Editor-Conf Check
        run: ec -version

        
