on: 
  push

jobs:

  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Flake8
        run: |
          pip install --upgrade pip
          pip install flake8

      - name: Run Flake8 checks
        run: flake8 src/app_test.py


  editorconfig_lint:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install EditorConfig Checker
        run: |
          curl -sSL https://github.com/editorconfig-checker/editorconfig-checker/releases/latest/download/ec-linux-amd64.tar.gz | tar -xz
          sudo mv ec-linux-amd64 /usr/local/bin/editorconfig-checker

      - name: Validate .editorconfig
        run: editorconfig-checker .
  
    
  test:
   runs-on: ubuntu-latest

   steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9  # Версията на Python може да бъде променена, ако е необходимо

    # Install dependencies
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt

    # Run unit tests
    - name: Run Unit Tests
      run: |
        python3 -m unittest discover -s src -p "app_test.py"
  
