on: 
  push

jobs:

  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Flake8
        run: |
          pip install --upgrade pip
          pip install flake8

      - name: Run Flake8 checks
        run: flake8 src/app_test.py

  editorconfig_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Editor-Conf-Checker
        run: pip install editorconfig-checker

      - name: Editor-Conf Check
        run: ec -version
        
  markdown_file_check:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Markdown Link Validation
      uses: ruzickap/action-my-markdown-link-checker@v1.1.2
      
  database_migrations:
  
    runs-on: ubuntu-latest
    needs: [linting, editorconfig_lint, markdown_file_check]
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: joshuaavalon/flyway-action@v3.0.0
        with:
          url: jdbc:postgresql://postgres:5432/db
          user: user
          password: password
      - run: echo 'testing'

  unit_testing:
    runs-on: ubuntu-latest
    needs: [linting, markdown_file_check, editorconfig_lint]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ./src/requirements.txt

      - name: Run tests
        run: |
          export PYTHONPATH=./src
          python3 -m unittest src/app_test.py


  SonarCloudTest:
    runs-on: ubuntu-latest
    permissions:
     packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v2.0.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_PROJECT_KEY: "python-docker-app"  # Твоят проектен ключ
        SONAR_ORG_KEY: "RositsaKostova"        # Твоята организация
        SONAR_HOST_URL: "https://sonarcloud.io"

